language: node_js
node_js:
  - "node"
install:
  - npm install
script:
  - npm run generate
cache:
  directories:
    - "node_modules"
branches:
  only:
  - master
deploy:
  repo: Statismic/statismic.github.io
  provider: pages
  local-dir: dist
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
notifications:
  email:
    recipients:
      - lherman.cs@gmail.com
      - gestewa@g.clemson.edu
    on_success: always # default: change
    on_failure: always # default: always